fix: update all_together.md
The command in the prior tab creates a validators/post.ts, rather than the validators/posts.ts file your sample code expects.

As a result the code currently on the homepage returns a type error:

"Cannot find module '#validators/posts' or its corresponding type declarations."